name: Lotto Auto Scraper

on:
  schedule:
    - cron: '30 12 * * 6' # 한국 시간: 토요일 오후 9시 30분
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 불러오기
        uses: actions/checkout@v3

      - name: 파이썬 환경 세팅
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 필수 라이브러리 설치
        run: |
          pip install selenium webdriver-manager beautifulsoup4 gspread google-auth

      - name: 금고에서 secret.json 꺼내서 생성하기
        run: |
          echo "${{ secrets.GCP_SECRET_JSON }}" > secret.json

      - name: 로또 파이썬 스크립트 실행!
        run: python lotto_auto.py
